name: 🚀 Release Trigger

on:
  workflow_dispatch:

jobs:
  call-release-trigger:
    uses: ynput/automation/reusable_workflows/release_trigger.yml@main
    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
      email: ${{ secrets.CI_EMAIL }}
      user: ${{ secrets.CI_USER }}