name: 🌟 Intial Release Trigger

on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        description: "Create the release as draft"
        required: false
        default: true

jobs:
  call-release-trigger:
    uses: ynput/automation/.github/workflows/initial_release_trigger.yml@main
    inputs:
      draft: ${{ inputs.draft }}
    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
      email: ${{ secrets.CI_EMAIL }}
      user: ${{ secrets.CI_USER }}
