name: 🚀 Release Trigger

on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        description: "Create Release Draft"
        required: false
        default: true
      version_overwrite:
        type: string
        description: "Set Version Release Tag"
        required: false

jobs:
  call-release-trigger:
    uses: ynput/ops-repo-automation/.github/workflows/release_trigger.yml@develop
    with:
      draft: ${{ inputs.draft }}
      version_overwrite: ${{ inputs.version_overwrite }}
    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
      email: ${{ secrets.CI_EMAIL }}
      user: ${{ secrets.CI_USER }}
